//Node对象
Node = function Node() {xzvm.toolsFunc.throwError("TypeError", "Illegal constructor")}
xzvm.toolsFunc.safeProto(Node,"Node");
Object.setPrototypeOf(Node.prototype, EventTarget.prototype);
xzvm.toolsFunc.defineProperty(Node, "ELEMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 1});
xzvm.toolsFunc.defineProperty(Node, "ATTRIBUTE_NODE", {enumerable: true, configurable: false,writable: false,value: 2});
xzvm.toolsFunc.defineProperty(Node, "TEXT_NODE", {enumerable: true, configurable: false,writable: false,value: 3});
xzvm.toolsFunc.defineProperty(Node, "CDATA_SECTION_NODE", {enumerable: true, configurable: false,writable: false,value: 4});
xzvm.toolsFunc.defineProperty(Node, "ENTITY_REFERENCE_NODE", {enumerable: true, configurable: false,writable: false,value: 5});
xzvm.toolsFunc.defineProperty(Node, "ENTITY_NODE", {enumerable: true, configurable: false,writable: false,value: 6});
xzvm.toolsFunc.defineProperty(Node, "PROCESSING_INSTRUCTION_NODE", {enumerable: true, configurable: false,writable: false,value: 7});
xzvm.toolsFunc.defineProperty(Node, "COMMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 8});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 9});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_TYPE_NODE", {enumerable: true, configurable: false,writable: false,value: 10});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_FRAGMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 11});
xzvm.toolsFunc.defineProperty(Node, "NOTATION_NODE", {enumerable: true, configurable: false,writable: false,value: 12});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_POSITION_DISCONNECTED", {enumerable: true, configurable: false,writable: false,value: 1});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_POSITION_PRECEDING", {enumerable: true, configurable: false,writable: false,value: 2});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_POSITION_FOLLOWING", {enumerable: true, configurable: false,writable: false,value: 4});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_POSITION_CONTAINS", {enumerable: true, configurable: false,writable: false,value: 8});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_POSITION_CONTAINED_BY", {enumerable: true, configurable: false,writable: false,value: 16});
xzvm.toolsFunc.defineProperty(Node, "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC", {enumerable: true, configurable: false,writable: false,value: 32});
xzvm.toolsFunc.defineProperty(Node.prototype, "nodeType", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","nodeType_get",arguments,9)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "nodeName", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","nodeName_get",arguments,"#document")},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "baseURI", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","baseURI_get",arguments,"https://newtab.uniontech.com/")},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "isConnected", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","isConnected_get",arguments,true)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "ownerDocument", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","ownerDocument_get",arguments,null)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "parentNode", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","parentNode_get",arguments,null)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "parentElement", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","parentElement_get",arguments,null)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "childNodes", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","childNodes_get",arguments)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "firstChild", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","firstChild_get",arguments)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "lastChild", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","lastChild_get",arguments)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "previousSibling", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","previousSibling_get",arguments,null)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "nextSibling", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","nextSibling_get",arguments,null)},set:undefined});
xzvm.toolsFunc.defineProperty(Node.prototype, "nodeValue", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","nodeValue_get",arguments,null)},set:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","nodeValue_set",arguments)}});
xzvm.toolsFunc.defineProperty(Node.prototype, "textContent", {enumerable: true, configurable: true,get:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","textContent_get",arguments,null)},set:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","textContent_set",arguments)}});
xzvm.toolsFunc.defineProperty(Node.prototype, "ELEMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 1});
xzvm.toolsFunc.defineProperty(Node.prototype, "ATTRIBUTE_NODE", {enumerable: true, configurable: false,writable: false,value: 2});
xzvm.toolsFunc.defineProperty(Node.prototype, "TEXT_NODE", {enumerable: true, configurable: false,writable: false,value: 3});
xzvm.toolsFunc.defineProperty(Node.prototype, "CDATA_SECTION_NODE", {enumerable: true, configurable: false,writable: false,value: 4});
xzvm.toolsFunc.defineProperty(Node.prototype, "ENTITY_REFERENCE_NODE", {enumerable: true, configurable: false,writable: false,value: 5});
xzvm.toolsFunc.defineProperty(Node.prototype, "ENTITY_NODE", {enumerable: true, configurable: false,writable: false,value: 6});
xzvm.toolsFunc.defineProperty(Node.prototype, "PROCESSING_INSTRUCTION_NODE", {enumerable: true, configurable: false,writable: false,value: 7});
xzvm.toolsFunc.defineProperty(Node.prototype, "COMMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 8});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 9});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_TYPE_NODE", {enumerable: true, configurable: false,writable: false,value: 10});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_FRAGMENT_NODE", {enumerable: true, configurable: false,writable: false,value: 11});
xzvm.toolsFunc.defineProperty(Node.prototype, "NOTATION_NODE", {enumerable: true, configurable: false,writable: false,value: 12});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_POSITION_DISCONNECTED", {enumerable: true, configurable: false,writable: false,value: 1});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_POSITION_PRECEDING", {enumerable: true, configurable: false,writable: false,value: 2});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_POSITION_FOLLOWING", {enumerable: true, configurable: false,writable: false,value: 4});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_POSITION_CONTAINS", {enumerable: true, configurable: false,writable: false,value: 8});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_POSITION_CONTAINED_BY", {enumerable: true, configurable: false,writable: false,value: 16});
xzvm.toolsFunc.defineProperty(Node.prototype, "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC", {enumerable: true, configurable: false,writable: false,value: 32});
xzvm.toolsFunc.defineProperty(Node.prototype, "appendChild", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","appendChild",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "cloneNode", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","cloneNode",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "compareDocumentPosition", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","compareDocumentPosition",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "contains", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","contains",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "getRootNode", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","getRootNode",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "hasChildNodes", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","hasChildNodes",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "insertBefore", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","insertBefore",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "isDefaultNamespace", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","isDefaultNamespace",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "isEqualNode", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","isEqualNode",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "isSameNode", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","isSameNode",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "lookupNamespaceURI", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","lookupNamespaceURI",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "lookupPrefix", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","lookupPrefix",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "normalize", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","normalize",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "removeChild", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","removeChild",arguments);}});
xzvm.toolsFunc.defineProperty(Node.prototype, "replaceChild", {enumerable: true, configurable: true,writable: true,value:function (){return xzvm.toolsFunc.dispatch(this,Node.prototype,"Node","replaceChild",arguments);}});
